version: '3.8'

services:
  
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - REDIS_URL=redis://redis:6379
    depends_on:
      - elasticsearch
      - redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  esdata: